In [1]:
# Dependencies
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
#load the full dataset and conduct data cleaning
train_data=pd.read_csv('Resources/train.csv')

In [6]:
#descriptives of train_data to spot any thing that requires cleaning
train_data.describe()

,fare_amount,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
count,5.542386e+07,5.542386e+07,5.542386e+07,5.542348e+07,5.542348e+07,5.542386e+07
mean,1.134505e+01,-7.250968e+01,3.991979e+01,-7.251121e+01,3.992068e+01,1.685380e+00
std,2.071083e+01,1.284888e+01,9.642353e+00,1.278220e+01,9.633346e+00,1.327664e+00
min,-3.000000e+02,-3.442060e+03,-3.492264e+03,-3.442025e+03,-3.547887e+03,0.000000e+00
25%,6.000000e+00,-7.399207e+01,4.073493e+01,-7.399140e+01,4.073403e+01,1.000000e+00
50%,8.500000e+00,-7.398180e+01,4.075265e+01,-7.398015e+01,4.075316e+01,1.000000e+00
75%,1.250000e+01,-7.396708e+01,4.076713e+01,-7.396367e+01,4.076810e+01,2.000000e+00
max,9.396336e+04,3.457626e+03,3.408790e+03,3.457622e+03,3.537133e+03,2.080000e+02

In [3]:
#drop the rows that fares are negative or equal to 0
train_cleaned = train_data.drop(train_data[train_data['fare_amount']<=0].index)

#making sure all pick-up and drop-off are based inside New York City.
#New York City latitude and longitude range is: North Latitude: 40.917577 South Latitude: 40.477399 East Longitude: -73.700272 West Longitude: -74.259090
#Source: https://www.mapdevelopers.com/geocode_bounding_box.php
#Data out of the range will be cleaned out
train_cleaned = train_cleaned.drop(train_cleaned[train_cleaned['pickup_longitude']>-73.700272].index)
train_cleaned = train_cleaned.drop(train_cleaned[train_cleaned['pickup_longitude']<-74.259090].index)
train_cleaned = train_cleaned.drop(train_cleaned[train_cleaned['dropoff_longitude']>-73.700272].index)
train_cleaned = train_cleaned.drop(train_cleaned[train_cleaned['dropoff_longitude']<-74.259090].index)
train_cleaned = train_cleaned.drop(train_cleaned[train_cleaned['pickup_latitude']>40.917577].index)
train_cleaned = train_cleaned.drop(train_cleaned[train_cleaned['pickup_latitude']<40.477399].index)
train_cleaned = train_cleaned.drop(train_cleaned[train_cleaned['dropoff_latitude']>40.917577].index)
train_cleaned = train_cleaned.drop(train_cleaned[train_cleaned['dropoff_latitude']<40.477399].index)

In [4]:
#cleaned out the fare > 500
train_cleaned = train_cleaned.drop(train_cleaned[train_cleaned['fare_amount']>500].index)

In [5]:
#cleaend out passenger_count > 9
train_cleaned = train_cleaned.drop(train_cleaned[train_cleaned['passenger_count']>9].index)
#clean out the passenger == 0 data
train_cleaned = train_cleaned.drop(train_cleaned[train_cleaned['passenger_count']==0].index)
#final clean data descriptives
train_cleaned.describe()

,fare_amount,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
count,5.399312e+07,5.399312e+07,5.399312e+07,5.399312e+07,5.399312e+07,5.399312e+07
mean,1.129027e+01,-7.397550e+01,4.075085e+01,-7.397463e+01,4.075120e+01,1.691312e+00
std,9.462680e+00,3.445888e-02,2.689724e-02,3.385423e-02,3.073171e-02,1.307169e+00
min,1.000000e-02,-7.425903e+01,4.047759e+01,-7.425905e+01,4.047765e+01,1.000000e+00
25%,6.000000e+00,-7.399228e+01,4.073657e+01,-7.399159e+01,4.073558e+01,1.000000e+00
50%,8.500000e+00,-7.398210e+01,4.075336e+01,-7.398062e+01,4.075384e+01,1.000000e+00
75%,1.250000e+01,-7.396835e+01,4.076752e+01,-7.396542e+01,4.076837e+01,2.000000e+00
max,5.000000e+02,-7.370028e+01,4.091754e+01,-7.370028e+01,4.091756e+01,9.000000e+00

In [6]:
#export the final cleaned data to csv
train_cleaned.to_csv('Resources/train_data_cleaned.csv')

In [7]:
#sample 25% of the training data
sample_data = train_data.sample(frac=.25)
sample_data.to_csv("Resources/sample_data_cleaned.csv")